apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-frontend-repo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-frontend-repo
  template:
    metadata:
      labels:
        app: graphql-frontend-repo
    spec:
      containers:
        - name: graphql-frontend-repo-container-1
          image: jaybhingradiya7/graphql-frontend-repo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-frontend-repo-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: graphql-frontend-repo
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
